baseURL = "https://softwhat.com/"
copyright = "© 2016 Alex Pulver"
enableEmoji = true
googleAnalytics = "UA-78532010-1"
languageCode = "en-us"
publishDir = "docs"
title = "SoftWhat?"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  # Blog subtitle which appears below blog title. Supports markdown.
  subtitle = "Architecture and Software Engineering tidbits"

  # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
  favicon = "icons/favicon.ico"

[permalinks]
  posts = "/:title"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/alexpulver"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/alexpulver"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/alex_pulver"

# Enable tags.
[taxonomies]
  tag = "tags"
